name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build CI (Push)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup cmake
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "cmake;3.22.1" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          ./gradlew :app:synthesizeDistDebugApksCI
          echo "APK_FILE_ARM32=$(find app/build/outputs/ci -name '*arm32.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARM64=$(find app/build/outputs/ci -name '*arm64.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARMALL=$(find app/build/outputs/ci -name '*armAll.apk')" >> $GITHUB_ENV
          echo "APK_FILE_UNIVERSAL=$(find app/build/outputs/ci -name '*universal.apk')" >> $GITHUB_ENV

      - name: Upload Artifacts(arm32)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.APK_FILE_ARM32 }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-arm32
      - name: Upload Artifacts(arm64)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.APK_FILE_ARM64 }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-arm64
      - name: Upload Artifacts(armAll)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.APK_FILE_ARMALL }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-armAll
      - name: Upload Artifacts(universal)
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.APK_FILE_UNIVERSAL }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-universal
